### ISSUE TITLE
Unable to install SIERRA

### ISSUE THREAD

**Issue by highacid** [rudix-mac/rudix#66]
```
cosmicsound:TXT CS$ sudo python rudix.py install rudix
cosmicsound:TXT CS$ rudix help
-bash: rudix: command not found
cosmicsound:TXT CS$
```

I have python 2.7

**Comment by anddam** [comment]
Have you checked the content of rudix.py?

**Comment by ruda** [comment]
Hi, unfortunelly -- because I don't have hardware for that -- the macOS Sierra is currently unsupported in Rudix. But if you download the `rudix.py` script you may able to install packages from Mac OS 10.11 El Capitan, by running this: `sudo OSX_VERSION=10.11 rudix.py install wget` (where wget is the package you want to install). I think they will run quite well on Sierra.

**Comment by ruda** [comment]
There is a initital support for Sierra now (ports, packages and package manager). By initial support I mean, the packages compiled for El Capitan is now available to Sierra too.

**Comment by anddam** [comment]
Thanks.
